# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
